# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: build
  steps:
    - script: docker build -t template .

- job: test
  steps:
    - script: docker run --name=template-test template 
      displayName: 'run the tests'

    - script: docker cp tepmlate-test:/usr/src/template/build_tmp/Testing .
      displayName: 'copy the test results'
    
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'CTest'
        testResultsFiles: '**/Testing/*/Test.xml'

    - script: docker rm template-test 
      displayName: 'clean the image'
      condition: always()

    - script: docker rmi template --force
      displayName: 'clean the container'
      condition: always()
