# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:
  - script: docker build -t template_$(Build.BuildId) .
    displayName: 'build the code'
  - script: docker run --name=template-test-$(Build.BuildId) template_$(Build.BuildId) 
    displayName: 'run the tests'

  - script: docker cp template-test-$(Build.BuildId):/usr/src/template/build_tmp/Testing .
    displayName: 'copy the test results'
  
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'CTest'
      testResultsFiles: '**/Testing/*/Test.xml'

  - script: |
      git clone --depth 1 -b gh-pages https://$(GITHUB_TOKEN)@github.com/XiangpengHao/cpp-template.git gh-pages

  - script: docker rm template-test-$(Build.BuildId) 
    displayName: 'clean the image'
    condition: always()

  - script: docker rmi template_$(Build.BuildId) --force
    displayName: 'clean the container'
    condition: always()
